#!/bin/bash

# creation of a variable to keep tracks of errors
NOW=$(date +"%F")
exec 1>> log-file/$NOW-sortie.log
exec 2>> log-file/$NOW-ERREUR.log

# connection to the ftp server, be careful, the password is in plaintext
/usr/bin/lftp ftp://USER:PASS@FTP-SERVEUR -e "mirror -x SOURCE/ / /TARGET/"
